### ISSUE TITLE
Ability to create note when nothing was found

### ISSUE THREAD

**Issue by papanikge** [sballin/alfred-search-notes-app#9]
Create a new file with the query as the title if nothing was found

This will emulate something like [Notational Velocity](http://notational.net) very well.

**Comment by sballin** [comment]
I too come from Notational Velocity and would like to have this feature, but it doesn't seem possible with the current architecture: https://www.alfredforum.com/topic/9695-fallback-action-when-script-filter-has-no-results/

I like having the results filtered by Alfred because the alternative would be to reopen the Notes SQL database on every keystroke, and I don't want performance to suffer because of that. I'll do some tests to see if it's feasible.

**Comment by clicseo** [comment]
And to simply have the possibility to add a new note from Alfred? Thanks

**Comment by sballin** [comment]
Added this feature in version 3.0.0!
